version: '3'
services:
  node-pacs-viewer-url-generator:
    container_name: pacs-viewer-url-generator
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      POSTGRES_HOST: 200.127.57.176
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
